# for converting srf to fasta format
#----------------------------------------------------------------------
#
rule master :
	input : '100401_EAS51_0210_FC6142HAAXX-1.fasta'

# perform the conversion
rule convert :
	input : '{pattern}.srf'
	output : '{pattern}.fasta'
	shell : 'srf2fasta {input} > {output}'
