types = ['giab']
sizes = [1, 2]
programs = ['ble', 'beetl2', 'egap', 'egsa', 'beetl']
beetl_tmp = expand("beetloutput-{letter}0{num}", letter=['B', 'L'], num=[0,1,2,3,4,5])
ble_tmp = expand("bin/tests/{dir}/*", dir = ['arrays', 'BWT', 'outputFiles', 'supportBWT', 'supportFiles', 'supportLCP', 'supportLists'])



from psutil import virtual_memory

ram = virtual_memory().total  # total physical memory available
memory = int(min(ram * 0.9 / (1024 ** 2), 4096))

rule all:
    input:
        expand("log/{type}/{size}/{program}/time.txt",
               type = types, size = sizes, program = programs)

rule ble_pre:
    output:
        "tests/arrays/.placeholder",
        "tests/BWT/.placeholder",
        "tests/supportBWT/.placeholder",
        "tests/supportLists/.placeholder",
        "tests/supportLCP/.placeholder",
    shell:
        "touch {output}"

rule ble_lcp:
    input:
        "data/{type}-{size}.fasta.gz",
    output:
        "log/{type}/{size}/ble/time.txt"
    log:
        "log/{type}/{size}/ble/log.txt"
    benchmark:
        "log/{type}/{size}/ble/benchmark.txt"
    shell:
        "/usr/bin/time --verbose bin/ble {input} > {log} 2> {output} && rm -f {ble_tmp}"


rule beetl2_lcp:
    input:
        "data/{type}-{size}.fasta"
    output:
        "log/{type}/{size}/beetl2/time.txt"
    log:
        "log/{type}/{size}/beetl2/log.txt"
    benchmark:
        "log/{type}/{size}/beetl2/benchmark.txt"
    shell:
        "/usr/bin/time --verbose bin/BCR_LCP_GSA {input} beetl2output {memory} > {log} 2> {output}"


rule egap_lcp:
    input:
        "data/{type}-{size}.fasta"
    output:
        "log/{type}/{size}/egap/time.txt"
    log:
        "log/{type}/{size}/egap/log.txt"
    benchmark:
        "log/{type}/{size}/egap/benchmark.txt"
    shell:
        "/usr/bin/time --verbose bin/eGap -m {memory} {input} > {log} 2> {output}"


rule egsa_lcp:
    input:
        "data/{type}-{size}.fasta"
    output:
        "log/{type}/{size}/egsa/time.txt"
    log:
        "log/{type}/{size}/egsa/log.txt"
    benchmark:
        "log/{type}/{size}/egsa/benchmark.txt"
    shell:
        "/usr/bin/time --verbose bin/egsa {input} 0 > {log} 2> {output}"


rule beetl_lcp:
    input:
        "data/{type}-{size}.fasta"
    output:
        real = "log/{type}/{size}/beetl/time.txt"
    log:
        "log/{type}/{size}/beetl/log.txt"
    shell:
        "/usr/bin/time --verbose bin/beetl-bwt -i {input} -o beetloutput --output-format=ascii --generate-lcp > {log} 2> {output.real} && rm -f {beetl_tmp}"


rule create_test_dirs:
    output:
        "{dir}/.placeholder"
    shell:
        "touch {output}"

rule fastagz:
    input:
        "/home/gianluca/Documenti/AlgoLab/datasets/BWT+LCP/lcp/input/{type}/{type}-{size}.fasta.gz"
    output:
        temp("data/{type}-{size}.fasta.gz")
    shell: "cp {input} {output}"

rule fasta:
    input:
        "data/{type}-{size}.fasta.gz"
    output:
        temp("data/{type}-{size}.fasta")
    shell: "gunzip -k {input}"
